"""updated tool_call model

Revision ID: 0160c53a77a5
Revises: 06abe0a44735
Create Date: 2025-08-26 18:16:43.200344

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0160c53a77a5"
down_revision = "06abe0a44735"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tool_history", schema=None) as batch_op:
        batch_op.alter_column(
            "tool_input",
            existing_type=sa.TEXT(),
            type_=postgresql.JSON(astext_type=sa.Text()),
            postgresql_using="tool_input::json",  # <-- important
            nullable=True,
        )
        batch_op.alter_column(
            "tool_output",
            existing_type=sa.TEXT(),
            type_=postgresql.JSON(astext_type=sa.Text()),
            postgresql_using="tool_output::json",  # <-- important
            nullable=True,
        )
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tool_history", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False)
        )
        batch_op.alter_column(
            "tool_output",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            type_=sa.TEXT(),
            nullable=False,
        )
        batch_op.alter_column(
            "tool_input",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            type_=sa.TEXT(),
            nullable=False,
        )

    # ### end Alembic commands ###
